name: 'Wait'
description: 'Wait a designated number of milliseconds'

inputs:
  terraform_docs_version:
    description: 'Version of terraform-docs to use'
    required: false
    default: 'v0.16.0'

runs:
  using: 'node16'
  main: '../../../dist/index.js'