name: "WIP JS"

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: Comment on PR
    steps:
      - name: "Commenter"
        uses: actions/github-script@v6
        with:
          script: |
            var commentBody = ``
            commentBody += `aaa`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })