name: "WIP JS"

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: Comment on PR
    steps:
      - uses: actions/checkout@v3

      - name: Commenter
        uses: ./
