on:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: Install default terraform-docs
        uses: ./

      - name: Verify default terraform-docs
        run: |
          terraform-docs version

      - name: Install provided terraform-docs
        uses: ./
        with:
          terraform_docs_version: 'v0.14.0'

      - name: Verify provided terraform-docs
        run: |
          terraform-docs version