on:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - id: foo
        uses: actions/hello-world-composite-action@v1

      - id: bar
        uses: actions/hello-world-composite-action@v1
        with:
          terraform_docs_version: 'v0.14.0'
